name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v1
        with:
          path: target
          key: cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-build-
      - name: Build Blog
        run: cargo run
      - name: Deploy to GitHub Pages
        run: |
          cp CNAME ./site/
          rustc src/deploy.rs -o /tmp/deploy
          (cd site/ && /tmp/deploy)
        env:
          GITHUB_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        if: github.ref == 'refs/heads/master'
